import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Joke creation App',
  description: 'Generated by CSAT-5',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='from-white-100 from-40% via-sky-100 via-50% to-emerald-10 to-90% ...'> 
      <body className= {inter.className}>{children}</body>
    </html>
  )
}
